language: php

php:
 - 5.4
 - 5.5
 - hhvm
allow_failures:
 - hvm

before_script:
  - composer selfupdate
  - export COMPOSER_ROOT_VERSION=2.0.0-RC3
  - composer install --prefer-source

script:
  - bin/phpspec run
